# Generated by Django 5.0.7 on 2024-08-01 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('yandex', 'Yandex'), ('mailru', 'Mail.ru')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sent_date', models.CharField(max_length=50)),
                ('received_date', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('attachments', models.JSONField(default=list)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_integration.emailaccount')),
            ],
        ),
    ]
